# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/detached_agent.proto
# :nocov:

require "google/protobuf"

require "google/protobuf/empty_pb"
require "google/protobuf/timestamp_pb"

descriptor_data = "\n\x18lib/detached_agent.proto\x12\x0f\x41ikido.Zen.gRPC\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x02\n\nTrackInput\x12+\n\x07request\x18\x02 \x01(\x0b\x32\x18.Aikido.Zen.gRPC.RequestH\x00\x12'\n\x05route\x18\x03 \x01(\x0b\x32\x16.Aikido.Zen.gRPC.RouteH\x00\x12%\n\x04scan\x18\x04 \x01(\x0b\x32\x15.Aikido.Zen.gRPC.ScanH\x00\x12)\n\x06\x61ttack\x18\x05 \x01(\x0b\x32\x17.Aikido.Zen.gRPC.AttackH\x00\x12-\n\x08outbound\x18\x06 \x01(\x0b\x32\x19.Aikido.Zen.gRPC.OutboundH\x00\x12%\n\x04user\x18\x07 \x01(\x0b\x32\x15.Aikido.Zen.gRPC.UserH\x00\x12\x44\n\x14middleware_installed\x18\x08 \x01(\x0b\x32$.Aikido.Zen.gRPC.MiddlewareInstalledH\x00\x42\x06\n\x04type\"\t\n\x07Request\"?\n\x05Route\x12\x12\n\nroute_verb\x18\x01 \x01(\t\x12\x12\n\nroute_path\x18\x02 \x01(\t\x12\x0e\n\x06schema\x18\x03 \x01(\t\"?\n\x04Scan\x12\x11\n\tsink_name\x18\x01 \x01(\t\x12\x12\n\nhas_errors\x18\x02 \x01(\x08\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\",\n\x06\x41ttack\x12\x11\n\tsink_name\x18\x01 \x01(\t\x12\x0f\n\x07\x62locked\x18\x02 \x01(\x08\"&\n\x08Outbound\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"Y\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12+\n\x07seen_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\n\n\x02ip\x18\x05 \x01(\t\"(\n\x13MiddlewareInstalled\x12\x11\n\tinstalled\x18\x01 \x01(\x08\x32R\n\rDetachedAgent\x12\x41\n\nOnTracking\x12\x1b.Aikido.Zen.gRPC.TrackInput\x1a\x16.google.protobuf.Emptyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Aikido
  module Zen
    module GRPC
      TrackInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Aikido.Zen.gRPC.TrackInput").msgclass
      Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Aikido.Zen.gRPC.Request").msgclass
      Route = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Aikido.Zen.gRPC.Route").msgclass
      Scan = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Aikido.Zen.gRPC.Scan").msgclass
      Attack = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Aikido.Zen.gRPC.Attack").msgclass
      Outbound = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Aikido.Zen.gRPC.Outbound").msgclass
      User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Aikido.Zen.gRPC.User").msgclass
      MiddlewareInstalled = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Aikido.Zen.gRPC.MiddlewareInstalled").msgclass
    end
  end
end
