# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: lib/detached_agent.proto for package 'Aikido.Zen.gRPC'
# :nocov:

require "grpc"
require_relative "detached_agent_pb"

module Aikido
  module Zen
    module GRPC
      module DetachedAgent
        class Service
          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = "Aikido.Zen.gRPC.DetachedAgent"

          rpc :OnTracking, ::Aikido::Zen::GRPC::TrackInput, ::Google::Protobuf::Empty
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
