source "https://rubygems.org"

ruby "3.3.4"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "pg", "~> 1.1"
gem "sprockets-rails"
gem "puma"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "standard"
end

gem "aikido-firewall", path: "../..", require: !ENV["DISABLE_FIREWALL"]
