source "https://rubygems.org"

ruby "3.3.4"

gem "rails", "~> 7.1.3"
gem "mysql2", "~> 0.5"
gem "propshaft"
gem "puma"
gem "tailwindcss-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "standard"
end

gem "aikido-firewall", path: "../..", require: !ENV["DISABLE_FIREWALL"]
