default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: 127.0.0.1
  flags:
    - MULTI_STATEMENTS

development:
  <<: *default
  database: cats

test:
  <<: *default
  database: cats_test

production:
  <<: *default
  database: cats
