name: Publish new Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: "./.github/workflows/main.yml"
  release:
    runs-on: ubuntu-latest
    name: release-gem

    permissions:
      contents: write
      id-token: write

    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Configure the latest Gemfile
        run: bin/link_gemfile "$(cat .ruby-version)"
      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1
        with:
          bundler-cache: true
      - uses: rubygems/release-gem@a25424ba2ba8b387abc8ef40807c2c85b96cbe32 # v1
