name: Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: "./.github/workflows/main.yml"
  release:
    runs-on: ubuntu-latest
    name: release-gem

    permissions:
      contents: write
      id-token: write

    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Configure the latest Gemfile
        run: echo "BUNDLE_GEMFILE=${{ github.workspace }}/gemfiles/ruby-$(cat .ruby-version).gemfile" >> $GITHUB_ENV
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - uses: rubygems/release-gem@v1
