name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    uses: "./.github/workflows/main.yml"
  release:
    runs-on: ubuntu-latest
    name: release-gem

    permissions:
      contents: write
      id-token: write

    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - uses: rubygems/release-gem@v1
